name: Python application

on: push: branches: [ main ] pull_request: branches: [ main ]

jobs: build:

yaml
runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v2

- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: '3.10'

- name: Install dependencies
  run: |
    pip install --upgrade pip
    pip install -r backend/requirements.txt
    pip install -r backend/requirements-dev.txt

- name: Lint with flake8
  run: |
    pip install flake8
    flake8 backend/

- name: Run Tests
  run: |
    pytest backend/tests/
