version: '3.8'

services: backend: build: ./backend container_name: jewelry_scraper_backend restart: always env_file: - .env ports: - "5000:5000" volumes: - ./backend:/app - ./data:/app/data - ./logs:/app/logs depends_on: - redis - db

frontend: build: ./frontend container_name: jewelry_scraper_frontend restart: always env_file: - .env ports: - "3000:3000" volumes: - ./frontend:/app depends_on: - backend

db: image: postgres:13 container_name: jewelry_scraper_db restart: always environment: POSTGRES_USER: yourusername POSTGRES_PASSWORD: yourpassword POSTGRES_DB: jewelry_scraper volumes: - db_data:/var/lib/postgresql/data

redis: image: redis:6 container_name: jewelry_scraper_redis restart: always ports: - "6379:6379"

prometheus: image: prom/prometheus container_name: jewelry_scraper_prometheus restart: always volumes: - ./prometheus.yml:/etc/prometheus/prometheus.yml ports: - "9090:9090"

grafana: image: grafana/grafana container_name: jewelry_scraper_grafana restart: always ports: - "3001:3000" depends_on: - prometheus volumes: - grafana_data:/var/lib/grafana

volumes: db_data: grafana_data: 
